name: preview-docs
on:
  push:
    branches-ignore:
      - main
    paths:
      - 'docs/**'
jobs:
  preview-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Install Dependencies
        run: npm install --workspace=docs
      - name: Build the website
        run: npm run build --workspace=docs
      - name: Deploy to Cloudflare pages
        id: deploy
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: pages deploy docs/dist --project-name=nibbles-and-bites
        timeout-minutes: 5
      - name: Print the preview URLs
        uses: mshick/add-pr-comment@ffd016c7e151d97d69d21a843022fd4cd5b96fe5 # v3
        with:
          message: |
            ## Preview URLs

            Deployment URL: ${{ steps.deploy.outputs.deployment-url }}
            Deployment alias URL: ${{ steps.deploy.outputs.deployment-alias-url }}
